import { describe, expect, it } from "vitest";
import { buildDesiredMilestones } from "@/lib/milestones/engine";
import { reconcileMilestones, summarizePlan, type ExistingMilestone } from "@/lib/milestones/reconcile";
import { zonedToUtc } from "@/lib/time/zones";
import { makeFlightComponent, makeTrip } from "./fixtures";

function asExisting(
  trip: ReturnType<typeof makeTrip>,
  overrides: Record<string, Partial<ExistingMilestone>> = {},
): ExistingMilestone[] {
  return buildDesiredMilestones(trip).milestones.map((d, i) => ({
    id: `m_${i}`,
    key: d.key,
    title: d.title,
    dueAt: d.dueAt,
    state: "pending" as const,
    isAutoGenerated: true,
    ...(overrides[d.key] ?? {}),
  }));
}

describe("יצירת תיק — סעיף 6.1", () => {
  it("תיק חדש מייצר את כל אבני הדרך בבת אחת", () => {
    const trip = makeTrip();
    const plan = reconcileMilestones({
      existing: [],
      desired: buildDesiredMilestones(trip).milestones,
      now: trip.bookedAt,
    });
    expect(plan.create.length).toBeGreaterThan(15);
    expect(plan.update).toHaveLength(0);
    expect(plan.remove).toHaveLength(0);
  });
});

describe("תיק שנוצר מאוחר — סעיף 14", () => {
  it("אבני דרך שנולדות אחרי מועדן מסומנות, כדי שלא יציפו את המסך", () => {
    // לקוח שנסגר שבועיים לפני הטיסה: חצי מאבני הדרך כבר באיחור.
    const trip = makeTrip({ bookedAt: zonedToUtc("2026-07-27T08:00", "Asia/Jerusalem") });
    const plan = reconcileMilestones({
      existing: [],
      desired: buildDesiredMilestones(trip).milestones,
      now: trip.bookedAt,
    });

    const late = plan.create.filter((c) => c.bornLate);
    const onTime = plan.create.filter((c) => !c.bornLate);

    expect(late.map((c) => c.key)).toContain("offer_insurance"); // departure-60d, מזמן מאחור
    expect(onTime.map((c) => c.key)).toContain("send_documents"); // departure-14d, בדיוק היום
    expect(late.length).toBeGreaterThan(0);
    expect(onTime.length).toBeGreaterThan(0);
  });

  it("בעיית תוקף דרכון אף פעם לא מקובצת — היא באמת דחופה", () => {
    const trip = makeTrip({ bookedAt: zonedToUtc("2026-07-27T08:00", "Asia/Jerusalem") });
    trip.travelers[0].passportExpiry = zonedToUtc("2026-09-01T00:00", "Asia/Jerusalem");
    const plan = reconcileMilestones({
      existing: [],
      desired: buildDesiredMilestones(trip).milestones,
      now: trip.bookedAt,
    });
    const passport = plan.create.find((c) => c.key === "passport_expiry:t_1");
    expect(passport).toBeDefined();
    expect(passport!.bornLate).toBe(false);
  });
});

describe("עדכון עוגן — סעיף 6.5", () => {
  it("דחיית תאריך הטיסה מזיזה את כל אבני הדרך הפתוחות", () => {
    const before = makeTrip();
    const existing = asExisting(before);

    const after = makeTrip({
      departureAt: zonedToUtc("2026-08-17T06:20", "Asia/Jerusalem"),
      returnAt: zonedToUtc("2026-08-24T21:40", "Europe/Athens"),
      components: [
        makeFlightComponent({
          id: "c_out", direction: "outbound", airlineCode: "A3",
          departsAtLocal: "2026-08-17T06:20", departsTz: "Asia/Jerusalem",
        }),
        makeFlightComponent({
          id: "c_in", direction: "inbound", airlineCode: "A3",
          departsAtLocal: "2026-08-24T21:40", departsTz: "Europe/Athens",
        }),
        before.components[2],
      ],
    });

    const plan = reconcileMilestones({
      existing,
      desired: buildDesiredMilestones(after).milestones,
      now: new Date("2026-04-01T09:00:00Z"),
    });
    const summary = summarizePlan(plan, existing);

    const docs = plan.update.find((u) => u.key === "send_documents")!;
    expect(docs.moved).toBe(true);
    expect(docs.toDueAt.getTime() - docs.fromDueAt.getTime()).toBe(7 * 24 * 3_600_000);

    // אבני דרך שעוגנן הוא מועד ההזמנה לא זזות.
    expect(plan.update.find((u) => u.key === "check_visa_requirements")!.moved).toBe(false);
    // וגם לא דדליין של ספק, שהוא מועד עצמאי.
    expect(plan.update.find((u) => u.key === "component_free_cancel:c_hotel")!.moved).toBe(false);

    expect(summary.movedCount).toBeGreaterThan(5);
    expect(summary.moves[0].deltaMinutes).toBe(7 * 24 * 60);
  });

  it("אבני דרך שכבר בוצעו לא זזות", () => {
    const before = makeTrip();
    const existing = asExisting(before, {
      send_documents: { state: "done" },
      offer_insurance: { state: "skipped" },
    });

    const after = makeTrip({ departureAt: zonedToUtc("2026-08-17T06:20", "Asia/Jerusalem") });
    const plan = reconcileMilestones({
      existing,
      desired: buildDesiredMilestones(after).milestones,
      now: new Date("2026-04-01T09:00:00Z"),
    });

    const docs = plan.update.find((u) => u.key === "send_documents")!;
    expect(docs.moved).toBe(false);
    expect(docs.toDueAt.getTime()).toBe(docs.fromDueAt.getTime());
    expect(summarizePlan(plan, existing).frozenCount).toBe(2);
  });
});

describe("שינוי רכיבים", () => {
  it("מחיקת רכיב מסירה את הדדליינים שלו", () => {
    const before = makeTrip();
    const existing = asExisting(before);
    const after = makeTrip({ components: before.components.slice(0, 2) });

    const plan = reconcileMilestones({
      existing,
      desired: buildDesiredMilestones(after).milestones,
      now: new Date("2026-04-01T09:00:00Z"),
    });

    expect(plan.remove.map((r) => r.key).sort()).toEqual([
      "component_free_cancel:c_hotel",
      "component_payment_due:c_hotel",
    ]);
  });

  it("דדליין של רכיב שכבר טופל נשמר כהיסטוריה ולא נמחק", () => {
    const before = makeTrip();
    const existing = asExisting(before, {
      "component_free_cancel:c_hotel": { state: "done" },
    });
    const after = makeTrip({ components: before.components.slice(0, 2) });

    const plan = reconcileMilestones({
      existing,
      desired: buildDesiredMilestones(after).milestones,
      now: new Date("2026-04-01T09:00:00Z"),
    });

    expect(plan.remove.map((r) => r.key)).toEqual(["component_payment_due:c_hotel"]);
  });

  it("הוספת טיסה יוצרת את אבני הדרך של הצ'ק-אין בדיעבד", () => {
    const withoutFlights = makeTrip({ components: [] });
    const existing = asExisting(withoutFlights);
    const withFlights = makeTrip();

    const plan = reconcileMilestones({
      existing,
      desired: buildDesiredMilestones(withFlights).milestones,
      now: new Date("2026-04-01T09:00:00Z"),
    });

    expect(plan.create.map((c) => c.key)).toContain("checkin_outbound_opens");
    expect(plan.create.map((c) => c.key)).toContain("checkin_outbound_closes");
    expect(plan.create.map((c) => c.key)).toContain("checkin_inbound_reminder");
  });
});
