"use server";

import { redirect } from "next/navigation";
import { z } from "zod";
import { prisma } from "@/lib/db";
import { refreshTripStates } from "@/lib/milestones/sync";
import { DISPLAY_TZ, zonedToUtc } from "@/lib/time/zones";

const schema = z.object({
  tripId: z.string().trim().min(1, "צריך לבחור נסיעה"),
  title: z.string().trim().min(2, "צריך לכתוב מה המשימה"),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "צריך תאריך"),
  time: z.string().regex(/^\d{2}:\d{2}$/).optional().or(z.literal("")),
  audience: z.enum(["agent", "client"]).default("agent"),
});

export type NewTaskState = { error?: string };

/** ברירת מחדל סבירה לשעה: תחילת יום העבודה, לא חצות. */
const DEFAULT_TIME = "09:00";

export async function createTaskAction(
  _prev: NewTaskState,
  formData: FormData,
): Promise<NewTaskState> {
  const parsed = schema.safeParse(Object.fromEntries(formData));
  if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? "חסרים פרטים" };

  const { tripId, title, date, time, audience } = parsed.data;

  const trip = await prisma.trip.findUnique({ where: { id: tripId }, select: { id: true } });
  if (!trip) return { error: "הנסיעה לא נמצאה" };

  const dueAt = zonedToUtc(`${date}T${time || DEFAULT_TIME}`, DISPLAY_TZ);

  /*
   * מפתח ייחודי לתיק, כי המסד אוכף @@unique([tripId, key]). הוא מתחיל
   * ב-manual_ כדי שיהיה אפשר לזהות במבט אחד מה נוצר ביד ומה מהתבנית.
   */
  const key = `manual_${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`;

  await prisma.milestone.create({
    data: {
      tripId,
      key,
      title,
      audience,
      anchor: "absolute",
      dueAt,
      state: "pending",
      /*
       * הדגל הזה הוא מה שמגן על המשימה: ההתאמה מחדש של אבני הדרך מוחקת
       * רק מה שהיא עצמה יצרה, ולכן משימה ידנית שורדת גם שינוי תאריך טיסה.
       */
      isAutoGenerated: false,
    },
  });

  // מיד אחרי היצירה קובעים את המצב האמיתי — משימה לתאריך שעבר היא כבר
  // באיחור, ולא "עתידית" שתמתין ליום הבא.
  await refreshTripStates(tripId);

  redirect(`/trips/${tripId}`);
}
