-- CreateTable
CREATE TABLE "Client" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "email" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Client_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Trip" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "destination" TEXT NOT NULL,
    "templateId" TEXT NOT NULL,
    "departureAt" TIMESTAMP(3) NOT NULL,
    "departureLocal" TEXT NOT NULL,
    "departureTz" TEXT NOT NULL,
    "departureAirport" TEXT NOT NULL,
    "returnAt" TIMESTAMP(3) NOT NULL,
    "returnLocal" TEXT NOT NULL,
    "returnTz" TEXT NOT NULL,
    "returnAirport" TEXT NOT NULL,
    "eventAt" TIMESTAMP(3),
    "eventLocal" TEXT,
    "eventTz" TEXT,
    "bookedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" TEXT NOT NULL DEFAULT 'active',
    "priceToClient" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "supplierCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "amountPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "expectedCommission" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "actualCommission" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "source" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Trip_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Traveler" (
    "id" TEXT NOT NULL,
    "tripId" TEXT NOT NULL,
    "firstNameLatin" TEXT NOT NULL,
    "lastNameLatin" TEXT NOT NULL,
    "displayNameHe" TEXT,
    "dateOfBirth" TIMESTAMP(3),
    "passportNumberEnc" TEXT,
    "passportLast4" TEXT,
    "passportExpiry" TIMESTAMP(3),
    "passportCountry" TEXT,
    "phone" TEXT,
    "isLead" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Traveler_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Component" (
    "id" TEXT NOT NULL,
    "tripId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "supplier" TEXT,
    "reference" TEXT,
    "description" TEXT,
    "status" TEXT NOT NULL DEFAULT 'requested',
    "freeCancelUntil" TIMESTAMP(3),
    "supplierPaymentDue" TIMESTAMP(3),
    "cost" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "price" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "isUpsell" BOOLEAN NOT NULL DEFAULT false,
    "clientResponse" TEXT,
    "declinedAt" TIMESTAMP(3),
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Component_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Flight" (
    "componentId" TEXT NOT NULL,
    "airlineCode" TEXT NOT NULL,
    "flightNumber" TEXT NOT NULL,
    "direction" TEXT NOT NULL,
    "departsAtLocal" TEXT NOT NULL,
    "departsTz" TEXT NOT NULL,
    "departsAirport" TEXT NOT NULL,
    "departsAtUtc" TIMESTAMP(3) NOT NULL,
    "arrivesAtLocal" TEXT NOT NULL,
    "arrivesTz" TEXT NOT NULL,
    "arrivesAirport" TEXT NOT NULL,
    "arrivesAtUtc" TIMESTAMP(3) NOT NULL,
    "checkinOpensAt" TIMESTAMP(3),
    "checkinClosesAt" TIMESTAMP(3),
    "checkinOverridden" BOOLEAN NOT NULL DEFAULT false,
    "checkinDone" BOOLEAN NOT NULL DEFAULT false,
    "checkinDoneAt" TIMESTAMP(3),
    "baggageAllowance" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Flight_pkey" PRIMARY KEY ("componentId")
);

-- CreateTable
CREATE TABLE "Milestone" (
    "id" TEXT NOT NULL,
    "tripId" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "audience" TEXT NOT NULL,
    "anchor" TEXT NOT NULL,
    "anchorRef" TEXT,
    "anchorField" TEXT,
    "offsetMinutes" INTEGER NOT NULL DEFAULT 0,
    "leadMinutes" INTEGER NOT NULL DEFAULT 0,
    "dueAt" TIMESTAMP(3) NOT NULL,
    "state" TEXT NOT NULL DEFAULT 'pending',
    "blockRulesJson" TEXT,
    "blockedByJson" TEXT,
    "autoCompleteRule" TEXT,
    "skipReason" TEXT,
    "completedAt" TIMESTAMP(3),
    "snoozedUntil" TIMESTAMP(3),
    "snoozeReason" TEXT,
    "resolution" TEXT,
    "messageTemplateKey" TEXT,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT true,
    "bornLate" BOOLEAN NOT NULL DEFAULT false,
    "sortHint" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Milestone_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Trip_code_key" ON "Trip"("code");

-- CreateIndex
CREATE INDEX "Trip_status_departureAt_idx" ON "Trip"("status", "departureAt");

-- CreateIndex
CREATE INDEX "Trip_departureAt_idx" ON "Trip"("departureAt");

-- CreateIndex
CREATE INDEX "Traveler_tripId_idx" ON "Traveler"("tripId");

-- CreateIndex
CREATE INDEX "Component_tripId_idx" ON "Component"("tripId");

-- CreateIndex
CREATE INDEX "Component_freeCancelUntil_idx" ON "Component"("freeCancelUntil");

-- CreateIndex
CREATE INDEX "Component_supplierPaymentDue_idx" ON "Component"("supplierPaymentDue");

-- CreateIndex
CREATE INDEX "Milestone_state_dueAt_idx" ON "Milestone"("state", "dueAt");

-- CreateIndex
CREATE INDEX "Milestone_dueAt_idx" ON "Milestone"("dueAt");

-- CreateIndex
CREATE INDEX "Milestone_tripId_dueAt_idx" ON "Milestone"("tripId", "dueAt");

-- CreateIndex
CREATE UNIQUE INDEX "Milestone_tripId_key_key" ON "Milestone"("tripId", "key");

-- AddForeignKey
ALTER TABLE "Trip" ADD CONSTRAINT "Trip_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Traveler" ADD CONSTRAINT "Traveler_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Component" ADD CONSTRAINT "Component_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Flight" ADD CONSTRAINT "Flight_componentId_fkey" FOREIGN KEY ("componentId") REFERENCES "Component"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Milestone" ADD CONSTRAINT "Milestone_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE CASCADE;
