/**
 * השוואה בין אבני הדרך שקיימות בתיק לבין אלה שהתבנית והרכיבים מחייבים.
 * טהור. משמש גם ליצירת תיק (סעיף 6.1) וגם לעדכון עוגן (סעיף 6.5).
 */

import type { MilestoneState } from "../domain/types";
import { isNeverCollapsed, type DesiredMilestone } from "./engine";

export type ExistingMilestone = {
  id: string;
  key: string;
  title: string;
  dueAt: Date;
  state: MilestoneState;
  isAutoGenerated: boolean;
};

export type PlannedCreate = DesiredMilestone & { bornLate: boolean };

export type PlannedUpdate = {
  id: string;
  key: string;
  title: string;
  fromDueAt: Date;
  toDueAt: Date;
  desired: DesiredMilestone;
  /** האם המועד באמת זז — רק אלה נכנסים לסיכום שמוצג למשתמש. */
  moved: boolean;
};

export type PlannedRemoval = { id: string; key: string; title: string };

export type ReconcilePlan = {
  create: PlannedCreate[];
  update: PlannedUpdate[];
  remove: PlannedRemoval[];
};

const isTerminal = (s: MilestoneState) => s === "done" || s === "skipped";

export function reconcileMilestones(params: {
  existing: ExistingMilestone[];
  desired: DesiredMilestone[];
  now: Date;
}): ReconcilePlan {
  const { existing, desired, now } = params;
  const existingByKey = new Map(existing.map((e) => [e.key, e]));
  const desiredByKey = new Map(desired.map((d) => [d.key, d]));

  const plan: ReconcilePlan = { create: [], update: [], remove: [] };

  for (const d of desired) {
    const current = existingByKey.get(d.key);
    if (!current) {
      // סעיף 14 — תיק שנוצר מאוחר. אבן דרך שנולדת כבר אחרי מועדה מסומנת ככזו,
      // כדי שמסך היום יוכל לקבץ אותן במקום להציף 12 שורות אדומות.
      plan.create.push({
        ...d,
        bornLate: !isNeverCollapsed(d.key) && d.dueAt.getTime() < now.getTime(),
      });
      continue;
    }

    // סעיף 6.5 — אבני דרך שכבר בוצעו או נדחו לא זזות.
    const moved = !isTerminal(current.state) && current.dueAt.getTime() !== d.dueAt.getTime();
    plan.update.push({
      id: current.id,
      key: d.key,
      title: d.title,
      fromDueAt: current.dueAt,
      toDueAt: isTerminal(current.state) ? current.dueAt : d.dueAt,
      desired: d,
      moved,
    });
  }

  for (const e of existing) {
    if (desiredByKey.has(e.key)) continue;
    // לא נוגעים בהיסטוריה ולא במה שהסוכן הוסיף ביד.
    if (isTerminal(e.state) || !e.isAutoGenerated) continue;
    plan.remove.push({ id: e.id, key: e.key, title: e.title });
  }

  return plan;
}

export type AnchorChangeSummary = {
  movedCount: number;
  createdCount: number;
  removedCount: number;
  frozenCount: number;
  moves: Array<{ title: string; from: Date; to: Date; deltaMinutes: number }>;
};

/** סיכום "מה זז ולאן" להצגה אחרי שינוי תאריך — דרישה מפורשת בסעיף 6.5 ו-12. */
export function summarizePlan(plan: ReconcilePlan, existing: ExistingMilestone[]): AnchorChangeSummary {
  const moves = plan.update
    .filter((u) => u.moved)
    .map((u) => ({
      title: u.title,
      from: u.fromDueAt,
      to: u.toDueAt,
      deltaMinutes: Math.round((u.toDueAt.getTime() - u.fromDueAt.getTime()) / 60_000),
    }))
    .sort((a, b) => a.to.getTime() - b.to.getTime());

  return {
    movedCount: moves.length,
    createdCount: plan.create.length,
    removedCount: plan.remove.length,
    frozenCount: existing.filter((e) => isTerminal(e.state)).length,
    moves,
  };
}
