/**
 * הגשר בין מנוע אבני הדרך (טהור) למסד הנתונים.
 * כל שינוי בתיק — עוגן, רכיב, נוסע, תשלום — עובר דרך syncTrip.
 */

import { prisma } from "../db";
import type { MilestoneState } from "../domain/types";
import { checkinWindow } from "../airlines/checkin";
import {
  buildDesiredMilestones,
  deriveState,
  evaluateAutoComplete,
  evaluateBlockers,
  type Blocker,
  type TripSnapshot,
} from "./engine";
import {
  reconcileMilestones,
  summarizePlan,
  type AnchorChangeSummary,
  type ExistingMilestone,
} from "./reconcile";
import type { AutoCompleteRule, BlockRule } from "./template";

export async function loadTripSnapshot(tripId: string): Promise<TripSnapshot> {
  const trip = await prisma.trip.findUnique({
    where: { id: tripId },
    include: {
      travelers: true,
      components: { include: { flight: true }, orderBy: { sortOrder: "asc" } },
    },
  });
  if (!trip) throw new Error(`תיק לא נמצא: ${tripId}`);

  return {
    id: trip.id,
    code: trip.code,
    templateId: trip.templateId,
    bookedAt: trip.bookedAt,
    departureAt: trip.departureAt,
    returnAt: trip.returnAt,
    eventAt: trip.eventAt,
    priceToClient: trip.priceToClient,
    amountPaid: trip.amountPaid,
    components: trip.components.map((c) => ({
      id: c.id,
      type: c.type,
      status: c.status,
      supplier: c.supplier,
      description: c.description,
      freeCancelUntil: c.freeCancelUntil,
      supplierPaymentDue: c.supplierPaymentDue,
      isUpsell: c.isUpsell,
      clientResponse: c.clientResponse,
      flight: c.flight
        ? {
            direction: c.flight.direction as "outbound" | "inbound",
            airlineCode: c.flight.airlineCode,
            departsAtUtc: c.flight.departsAtUtc,
            checkinOpensAt: c.flight.checkinOpensAt,
            checkinClosesAt: c.flight.checkinClosesAt,
            checkinDone: c.flight.checkinDone,
          }
        : null,
    })),
    travelers: trip.travelers.map((t) => ({
      id: t.id,
      name: t.displayNameHe || `${t.firstNameLatin} ${t.lastNameLatin}`,
      passportExpiry: t.passportExpiry,
      hasPassportNumber: !!t.passportNumberEnc,
    })),
  };
}

/** מחשב מחדש את חלונות הצ'ק-אין של כל הטיסות בתיק, פרט לאלה שנדרסו ידנית. */
export async function recomputeCheckinWindows(tripId: string): Promise<void> {
  const flights = await prisma.flight.findMany({
    where: { component: { tripId } },
  });
  for (const f of flights) {
    if (f.checkinOverridden) continue;
    const win = checkinWindow({
      airlineCode: f.airlineCode,
      departsAtLocal: f.departsAtLocal,
      departsTz: f.departsTz,
    });
    if (
      f.checkinOpensAt?.getTime() === win.opensAt.getTime() &&
      f.checkinClosesAt?.getTime() === win.closesAt.getTime()
    ) {
      continue;
    }
    await prisma.flight.update({
      where: { componentId: f.componentId },
      data: { checkinOpensAt: win.opensAt, checkinClosesAt: win.closesAt },
    });
  }
}

function parseRules(json: string | null): BlockRule[] {
  if (!json) return [];
  try {
    return JSON.parse(json) as BlockRule[];
  } catch {
    return [];
  }
}

function parseAutoRule(json: string | null): AutoCompleteRule | null {
  if (!json) return null;
  try {
    return JSON.parse(json) as AutoCompleteRule;
  } catch {
    return null;
  }
}

/**
 * מסנכרן את אבני הדרך של תיק למצב הנכון ומחזיר סיכום "מה זז ולאן".
 * נקרא אחרי כל שינוי משמעותי בתיק, ובפרט אחרי שינוי departure_at (סעיף 6.5).
 */
export async function syncTrip(
  tripId: string,
  opts: { now?: Date } = {},
): Promise<AnchorChangeSummary> {
  const now = opts.now ?? new Date();

  await recomputeCheckinWindows(tripId);
  const snapshot = await loadTripSnapshot(tripId);
  const { milestones: desired } = buildDesiredMilestones(snapshot);

  const existingRows = await prisma.milestone.findMany({ where: { tripId } });
  const existing: ExistingMilestone[] = existingRows.map((m) => ({
    id: m.id,
    key: m.key,
    title: m.title,
    dueAt: m.dueAt,
    state: m.state as MilestoneState,
    isAutoGenerated: m.isAutoGenerated,
  }));

  const plan = reconcileMilestones({ existing, desired, now });
  const summary = summarizePlan(plan, existing);

  await prisma.$transaction(async (tx) => {
    for (const c of plan.create) {
      await tx.milestone.create({
        data: {
          tripId,
          key: c.key,
          title: c.title,
          audience: c.audience,
          anchor: c.anchor,
          anchorRef: c.anchorRef,
          anchorField: c.anchorField,
          offsetMinutes: c.offsetMinutes,
          leadMinutes: c.leadMinutes,
          dueAt: c.dueAt,
          state: "pending",
          blockRulesJson: c.blockRules.length ? JSON.stringify(c.blockRules) : null,
          autoCompleteRule: c.autoCompleteRule ? JSON.stringify(c.autoCompleteRule) : null,
          messageTemplateKey: c.messageTemplateKey,
          isAutoGenerated: true,
          bornLate: c.bornLate,
          sortHint: c.sortHint,
        },
      });
    }

    for (const u of plan.update) {
      await tx.milestone.update({
        where: { id: u.id },
        data: {
          title: u.desired.title,
          audience: u.desired.audience,
          anchor: u.desired.anchor,
          anchorRef: u.desired.anchorRef,
          anchorField: u.desired.anchorField,
          offsetMinutes: u.desired.offsetMinutes,
          leadMinutes: u.desired.leadMinutes,
          dueAt: u.toDueAt,
          blockRulesJson: u.desired.blockRules.length ? JSON.stringify(u.desired.blockRules) : null,
          autoCompleteRule: u.desired.autoCompleteRule ? JSON.stringify(u.desired.autoCompleteRule) : null,
          messageTemplateKey: u.desired.messageTemplateKey,
          sortHint: u.desired.sortHint,
        },
      });
    }

    if (plan.remove.length) {
      await tx.milestone.deleteMany({ where: { id: { in: plan.remove.map((r) => r.id) } } });
    }
  });

  await refreshTripStates(tripId, now);
  return summary;
}

/**
 * מחשב מחדש מצבי אבני דרך, חסימות והשלמות אוטומטיות לתיק אחד.
 * שתי מעברות: הראשונה קובעת done/overdue/due, השנייה מעריכה חסימות
 * שתלויות באבני דרך אחרות על בסיס המצבים המעודכנים.
 */
export async function refreshTripStates(tripId: string, now: Date = new Date()): Promise<number> {
  const snapshot = await loadTripSnapshot(tripId);
  const rows = await prisma.milestone.findMany({ where: { tripId } });

  const stateByKey = new Map<string, MilestoneState>(rows.map((r) => [r.key, r.state as MilestoneState]));
  let changed = 0;

  for (let pass = 0; pass < 2; pass++) {
    for (const row of rows) {
      const current = stateByKey.get(row.key) as MilestoneState;
      const blockers: Blocker[] = evaluateBlockers(snapshot, parseRules(row.blockRulesJson), stateByKey);
      const autoCompleted = evaluateAutoComplete(snapshot, parseAutoRule(row.autoCompleteRule));

      const next = deriveState({
        currentState: current,
        dueAt: row.dueAt,
        leadMinutes: row.leadMinutes,
        hasBlockers: blockers.length > 0,
        autoCompleted,
        now,
      });

      stateByKey.set(row.key, next);

      if (pass === 1) {
        const blockedJson = blockers.length ? JSON.stringify(blockers) : null;
        if (row.state !== next || row.blockedByJson !== blockedJson) {
          await prisma.milestone.update({
            where: { id: row.id },
            data: {
              state: next,
              blockedByJson: blockedJson,
              completedAt: next === "done" && !row.completedAt ? now : row.completedAt,
            },
          });
          changed++;
        }
      }
    }
  }

  return changed;
}

export function parseBlockers(json: string | null): Blocker[] {
  if (!json) return [];
  try {
    return JSON.parse(json) as Blocker[];
  } catch {
    return [];
  }
}
